# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Runner

  flutter_application_path = '../'
  load File.expand_path('../../.flutter-plugins-dependencies', __FILE__)

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
